// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Package postgres contains PostgreSQL-specific SQL parsing tests.
// These tests are ported from tests/sqlparser_postgres.rs in the Rust implementation.
package postgres

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/user/sqlparser/dialects"
	"github.com/user/sqlparser/dialects/generic"
	"github.com/user/sqlparser/dialects/postgresql"
	"github.com/user/sqlparser/parser"
	"github.com/user/sqlparser/tests/utils"
)

// pg returns a TestedDialects with only PostgreSQL dialect
func pg() *utils.TestedDialects {
	return &utils.TestedDialects{
		Dialects: []dialects.Dialect{
			postgresql.NewPostgreSqlDialect(),
		},
	}
}

// pgAndGeneric returns a TestedDialects with PostgreSQL and Generic dialects
func pgAndGeneric() *utils.TestedDialects {
	return &utils.TestedDialects{
		Dialects: []dialects.Dialect{
			postgresql.NewPostgreSqlDialect(),
			generic.NewGenericDialect(),
		},
	}
}

// TestPostgresCreateTableGeneratedAlwaysAsIdentity tests CREATE TABLE with GENERATED ALWAYS AS IDENTITY
// Reference: tests/sqlparser_postgres.rs:33
func TestPostgresCreateTableGeneratedAlwaysAsIdentity(t *testing.T) {
	pg := pg()

	// Note: Go implementation uses UPPERCASE for canonical form (matching Rust behavior)
	// Input uses lowercase, but canonical output is uppercase
	pg.OneStatementParsesTo(t,
		"CREATE TABLE table2 (column21 bigint primary key generated always as identity, column30 text)",
		"CREATE TABLE table2 (column21 BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, column30 TEXT)")

	pg.OneStatementParsesTo(t,
		"CREATE TABLE table2 (column21 bigint primary key generated by default as identity, column30 text)",
		"CREATE TABLE table2 (column21 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, column30 TEXT)")

	pg.OneStatementParsesTo(t,
		"CREATE TABLE table2 (column22 bigint generated always as identity, column30 text)",
		"CREATE TABLE table2 (column22 BIGINT GENERATED ALWAYS AS IDENTITY, column30 TEXT)")

	pg.OneStatementParsesTo(t,
		"CREATE TABLE table2 (column23 bigint generated by default as identity (INCREMENT 1 MINVALUE 1 MAXVALUE 20 START WITH 10 CACHE 2 NO CYCLE), column30 text)",
		"CREATE TABLE table2 (column23 BIGINT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 1 MAXVALUE 20 START WITH 10 CACHE 2 NO CYCLE), column30 TEXT)")
}

// TestPostgresCreateSequence tests CREATE SEQUENCE statements
// Reference: tests/sqlparser_postgres.rs:229
func TestPostgresCreateSequence(t *testing.T) {
	pg := pg()

	pg.VerifiedStmt(t, "CREATE SEQUENCE name0")
	pg.VerifiedStmt(t, "CREATE SEQUENCE IF NOT EXISTS name0")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE IF NOT EXISTS name0")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE name0")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE IF NOT EXISTS name1 AS BIGINT INCREMENT BY 1 MINVALUE 1 MAXVALUE 20 START WITH 10")
	pg.VerifiedStmt(t, "CREATE SEQUENCE IF NOT EXISTS name2 AS BIGINT INCREMENT 1 MINVALUE 1 MAXVALUE 20 START WITH 10 CACHE 2 NO CYCLE")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE IF NOT EXISTS name3 INCREMENT 1 NO MINVALUE MAXVALUE 20 CACHE 2 CYCLE")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE IF NOT EXISTS name3 INCREMENT 1 NO MINVALUE MAXVALUE 20 OWNED BY public.table01")
	pg.VerifiedStmt(t, "CREATE TEMPORARY SEQUENCE IF NOT EXISTS name3 INCREMENT 1 NO MINVALUE MAXVALUE 20 OWNED BY NONE")
	pg.VerifiedStmt(t, "CREATE SEQUENCE name4 AS BIGINT INCREMENT -15 MINVALUE -2000 MAXVALUE -50 START WITH -60")
	pg.VerifiedStmt(t, "CREATE SEQUENCE name5 AS BIGINT INCREMENT +10 MINVALUE +30 MAXVALUE +5000 START WITH +45")

	// Test error case
	dialect := postgresql.NewPostgreSqlDialect()
	_, err := parser.ParseSQL(dialect, "CREATE SEQUENCE foo INCREMENT 1 NO MINVALUE NO")
	require.Error(t, err)
}

// TestPostgresDropSequence tests DROP SEQUENCE statements
// Reference: tests/sqlparser_postgres.rs:314
func TestPostgresDropSequence(t *testing.T) {
	pg := pg()

	pg.VerifiedStmt(t, "DROP SEQUENCE IF EXISTS name0 CASCADE")
	pg.VerifiedStmt(t, "DROP SEQUENCE IF EXISTS name1 RESTRICT")
	pg.VerifiedStmt(t, "DROP SEQUENCE name2 CASCADE")
	pg.VerifiedStmt(t, "DROP SEQUENCE name2")
	pg.VerifiedStmt(t, "DROP SEQUENCE name0 CASCADE")
	pg.VerifiedStmt(t, "DROP SEQUENCE name1 RESTRICT")
	pg.VerifiedStmt(t, "DROP SEQUENCE name1, name2, name3")
}

// TestPostgresCreateTableWithDefaults tests CREATE TABLE with DEFAULT values
// Reference: tests/sqlparser_postgres.rs:333
func TestPostgresCreateTableWithDefaults(t *testing.T) {
	pg := pg()
	// Use canonical uppercase form for data types (Rust canonical form)
	sql := "CREATE TABLE public.customer (customer_id INTEGER DEFAULT nextval(public.customer_customer_id_seq), store_id SMALLINT NOT NULL, first_name CHARACTER VARYING(45) NOT NULL, last_name CHARACTER VARYING(45) COLLATE \"es_ES\" NOT NULL, email CHARACTER VARYING(50), address_id SMALLINT NOT NULL, activebool BOOLEAN DEFAULT true NOT NULL, create_date DATE DEFAULT now()::TEXT NOT NULL, last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, active INT NOT NULL) WITH (fillfactor = 20, user_catalog_table = true, autovacuum_vacuum_threshold = 100)"
	pg.VerifiedStmt(t, sql)
}

// TestPostgresCastInDefaultExpr tests CAST in DEFAULT expressions
// Reference: tests/sqlparser_postgres.rs:516
func TestPostgresCastInDefaultExpr(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TABLE t (c TEXT DEFAULT (foo())::TEXT)")
	pg.VerifiedStmt(t, "CREATE TABLE t (c TEXT DEFAULT (foo())::INT::TEXT)")
	pg.VerifiedStmt(t, "CREATE TABLE t (c TEXT DEFAULT (foo())::TEXT NOT NULL)")
}

// TestPostgresCreateTableFromPgDump tests CREATE TABLE from pg_dump
// Reference: tests/sqlparser_postgres.rs:523
func TestPostgresCreateTableFromPgDump(t *testing.T) {
	pg := pg()
	// Use canonical uppercase form for data types (Rust canonical form)
	sql := "CREATE TABLE public.customer (customer_id INTEGER DEFAULT nextval('public.customer_customer_id_seq'::regclass) NOT NULL, store_id SMALLINT NOT NULL, first_name CHARACTER VARYING(45) NOT NULL, last_name CHARACTER VARYING(45) NOT NULL, info TEXT[], address_id SMALLINT NOT NULL, activebool BOOLEAN DEFAULT true NOT NULL, create_date DATE DEFAULT now()::DATE NOT NULL, create_date1 DATE DEFAULT 'now'::TEXT::DATE NOT NULL, last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now(), release_year public.year, active INT)"
	pg.VerifiedStmt(t, sql)
}

// TestPostgresCreateTableWithInherit tests CREATE TABLE with INHERIT
// Reference: tests/sqlparser_postgres.rs:555
func TestPostgresCreateTableWithInherit(t *testing.T) {
	pg := pg()
	sql := "CREATE TABLE bazaar.settings (settings_id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL, user_id UUID UNIQUE, value TEXT[], use_metric BOOLEAN DEFAULT true)"
	pg.VerifiedStmt(t, sql)
}

// TestPostgresCreateTableEmpty tests CREATE TABLE with no columns
// Reference: tests/sqlparser_postgres.rs:567
func TestPostgresCreateTableEmpty(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t ()")
}

// TestPostgresCreateTableConstraintsOnly tests CREATE TABLE with constraints only
// Reference: tests/sqlparser_postgres.rs:574
func TestPostgresCreateTableConstraintsOnly(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (CONSTRAINT positive CHECK (2 > 1))")
}

// TestPostgresAlterTableConstraintsRename tests ALTER TABLE RENAME CONSTRAINT
// Reference: tests/sqlparser_postgres.rs:636
func TestPostgresAlterTableConstraintsRename(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "ALTER TABLE tab RENAME CONSTRAINT old_name TO new_name")
}

// TestPostgresAlterTableConstraintsUniqueNullsDistinct tests ALTER TABLE with UNIQUE NULLS DISTINCT
// Reference: tests/sqlparser_postgres.rs:649
func TestPostgresAlterTableConstraintsUniqueNullsDistinct(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ADD CONSTRAINT b UNIQUE NULLS NOT DISTINCT (c)")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ADD CONSTRAINT b UNIQUE NULLS DISTINCT (c)")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ADD CONSTRAINT b UNIQUE (c)")
}

// TestPostgresAlterTableConstraintUsingIndex tests ALTER TABLE with USING INDEX
// Reference: tests/sqlparser_postgres.rs:670
func TestPostgresAlterTableConstraintUsingIndex(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD CONSTRAINT c PRIMARY KEY USING INDEX my_index")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD CONSTRAINT c UNIQUE USING INDEX my_index")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD PRIMARY KEY USING INDEX my_index")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD UNIQUE USING INDEX my_index")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD CONSTRAINT c PRIMARY KEY USING INDEX my_index DEFERRABLE")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD CONSTRAINT c UNIQUE USING INDEX my_index NOT DEFERRABLE INITIALLY IMMEDIATE")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ADD CONSTRAINT c PRIMARY KEY USING INDEX my_index DEFERRABLE INITIALLY DEFERRED")
}

// TestPostgresAlterTableDisable tests ALTER TABLE DISABLE statements
// Reference: tests/sqlparser_postgres.rs:709
func TestPostgresAlterTableDisable(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab DISABLE ROW LEVEL SECURITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab DISABLE RULE rule_name")
}

// TestPostgresAlterTableDisableTrigger tests ALTER TABLE DISABLE TRIGGER
// Reference: tests/sqlparser_postgres.rs:715
func TestPostgresAlterTableDisableTrigger(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab DISABLE TRIGGER ALL")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab DISABLE TRIGGER USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab DISABLE TRIGGER trigger_name")
}

// TestPostgresAlterTableEnable tests ALTER TABLE ENABLE statements
// Reference: tests/sqlparser_postgres.rs:722
func TestPostgresAlterTableEnable(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE ALWAYS RULE rule_name")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE ALWAYS TRIGGER trigger_name")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE REPLICA TRIGGER trigger_name")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE REPLICA RULE rule_name")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE ROW LEVEL SECURITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab FORCE ROW LEVEL SECURITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab NO FORCE ROW LEVEL SECURITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE RULE rule_name")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE TRIGGER ALL")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE TRIGGER USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab ENABLE TRIGGER trigger_name")
}

// TestPostgresTruncateTable tests TRUNCATE TABLE statements
// Reference: tests/sqlparser_postgres.rs:737
func TestPostgresTruncateTable(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE TABLE \"users\", \"orders\" RESTART IDENTITY RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE users, orders RESTART IDENTITY")
}

// TestPostgresCreateExtension tests CREATE EXTENSION statements
// Reference: tests/sqlparser_postgres.rs:744
func TestPostgresCreateExtension(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH SCHEMA schema_name")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH VERSION version")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH CASCADE")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH SCHEMA schema_name VERSION version CASCADE")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH SCHEMA schema_name CASCADE")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH VERSION version CASCADE")
	pgAndGeneric.VerifiedStmt(t, "CREATE EXTENSION extension_name WITH SCHEMA schema_name VERSION version")
}

// TestPostgresDropExtension tests DROP EXTENSION statements
// Reference: tests/sqlparser_postgres.rs:760
func TestPostgresDropExtension(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION extension_name")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION extension_name CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION extension_name RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION extension_name, extension_name2 CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION extension_name, extension_name2 RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION IF EXISTS extension_name")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION IF EXISTS extension_name CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION IF EXISTS extension_name RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION IF EXISTS extension_name1, extension_name2 CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP EXTENSION IF EXISTS extension_name1, extension_name2 RESTRICT")
}

// TestPostgresAlterTableAlterColumn tests ALTER TABLE ALTER COLUMN
// Reference: tests/sqlparser_postgres.rs:854
func TestPostgresAlterTableAlterColumn(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "ALTER TABLE tab ALTER COLUMN is_active TYPE TEXT USING 'text'")
	pg.VerifiedStmt(t, "ALTER TABLE tab ALTER COLUMN is_active SET DATA TYPE TEXT USING 'text'")
}

// TestPostgresAlterTableAlterColumnAddGenerated tests ALTER TABLE ALTER COLUMN ADD GENERATED
// Reference: tests/sqlparser_postgres.rs:880
func TestPostgresAlterTableAlterColumnAddGenerated(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ALTER COLUMN id ADD GENERATED AS IDENTITY")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ALTER COLUMN id ADD GENERATED AS IDENTITY (INCREMENT 1 MINVALUE 1)")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE t ALTER COLUMN id ADD GENERATED AS IDENTITY ()")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()
	_, err := parser.ParseSQL(dialect, "ALTER TABLE t ALTER COLUMN id ADD GENERATED (INCREMENT 1 MINVALUE 1)")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "ALTER TABLE t ALTER COLUMN id ADD GENERATED AS IDENTITY (INCREMENT)")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "ALTER TABLE t ALTER COLUMN id ADD GENERATED AS IDENTITY (")
	require.Error(t, err)
}

// TestPostgresAlterTableAddColumns tests ALTER TABLE ADD COLUMN
// Reference: tests/sqlparser_postgres.rs:916
func TestPostgresAlterTableAddColumns(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "ALTER TABLE IF EXISTS ONLY tab ADD COLUMN a TEXT, ADD COLUMN b INT")
}

// TestPostgresAlterTableOwnerTo tests ALTER TABLE OWNER TO
// Reference: tests/sqlparser_postgres.rs:959
func TestPostgresAlterTableOwnerTo(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO new_owner")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO postgres")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO CREATE")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO \"new_owner\"")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO CURRENT_USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO CURRENT_ROLE")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE tab OWNER TO SESSION_USER")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()
	_, err := parser.ParseSQL(dialect, "ALTER TABLE tab OWNER TO CREATE FOO")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "ALTER TABLE tab OWNER TO 4")
	require.Error(t, err)
}

// TestPostgresCreateTableIfNotExists tests CREATE TABLE IF NOT EXISTS
// Reference: tests/sqlparser_postgres.rs:1031
func TestPostgresCreateTableIfNotExists(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE IF NOT EXISTS uk_cities ()")
}

// TestPostgresBadIfNotExists tests invalid IF NOT EXISTS syntax
// Reference: tests/sqlparser_postgres.rs:1047
func TestPostgresBadIfNotExists(t *testing.T) {
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "CREATE TABLE NOT EXISTS uk_cities ()")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "CREATE TABLE IF EXISTS uk_cities ()")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "CREATE TABLE IF uk_cities ()")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "CREATE TABLE IF NOT uk_cities ()")
	require.Error(t, err)
}

// TestPostgresCreateSchemaIfNotExists tests CREATE SCHEMA IF NOT EXISTS
// Reference: tests/sqlparser_postgres.rs:1074
func TestPostgresCreateSchemaIfNotExists(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE SCHEMA IF NOT EXISTS schema_name")
}

// TestPostgresDropSchemaIfExists tests DROP SCHEMA IF EXISTS
// Reference: tests/sqlparser_postgres.rs:1088
func TestPostgresDropSchemaIfExists(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "DROP SCHEMA IF EXISTS schema_name")
}

// TestPostgresCopyFromStdinWithoutSemicolon tests COPY FROM STDIN without semicolon
// Reference: tests/sqlparser_postgres.rs:1127
func TestPostgresCopyFromStdinWithoutSemicolon(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "COPY bitwise_test FROM STDIN NULL 'null'")
}

// TestPostgresCopyFromStdinWithoutSemicolonVariants tests various COPY FROM STDIN patterns
// Reference: tests/sqlparser_postgres.rs:1146
func TestPostgresCopyFromStdinWithoutSemicolonVariants(t *testing.T) {
	pg := pg()
	cases := []string{
		"COPY varbit_table FROM STDIN",
		"COPY bit_table FROM STDIN",
		"COPY copytest2 (test) FROM STDIN",
		"COPY copytest3 FROM STDIN CSV HEADER",
		"COPY copytest4 FROM STDIN (HEADER)",
		"COPY parted_copytest FROM STDIN",
		"COPY tab_progress_reporting FROM STDIN",
		"COPY oversized_column_default FROM STDIN",
		"COPY x (a, b, c, d, e) FROM STDIN",
		"COPY header_copytest (c, a) FROM STDIN",
		"COPY atest5 (two) FROM STDIN",
		"COPY main_table (a, b) FROM STDIN",
	}
	for _, sql := range cases {
		pg.VerifiedStmt(t, sql)
	}
}

// TestPostgresCopyFrom tests COPY FROM statements
// Reference: tests/sqlparser_postgres.rs:1183
func TestPostgresCopyFrom(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "COPY users FROM 'data.csv'")
	pg.VerifiedStmt(t, "COPY users FROM 'data.csv' DELIMITER ','")
	pg.VerifiedStmt(t, "COPY users FROM 'data.csv' DELIMITER ',' CSV HEADER")
}

// TestPostgresCopyTo tests COPY TO statements
// Reference: tests/sqlparser_postgres.rs:1243
func TestPostgresCopyTo(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "COPY users TO 'data.csv'")
	pg.VerifiedStmt(t, "COPY users TO 'data.csv' DELIMITER ','")
	pg.VerifiedStmt(t, "COPY users TO 'data.csv' DELIMITER ',' CSV HEADER")
}

// TestPostgresSet tests SET statements
// Reference: tests/sqlparser_postgres.rs:1580
func TestPostgresSet(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SET a = b")
	pgAndGeneric.VerifiedStmt(t, "SET a = 'b'")
	pgAndGeneric.VerifiedStmt(t, "SET a = 0")
	pgAndGeneric.VerifiedStmt(t, "SET a = DEFAULT")
	pgAndGeneric.VerifiedStmt(t, "SET LOCAL a = b")
	pgAndGeneric.VerifiedStmt(t, "SET a.b.c = b")
	pgAndGeneric.VerifiedStmt(t, "SET hive.tez.auto.reducer.parallelism = false")
	pgAndGeneric.OneStatementParsesTo(t, "SET a TO b", "SET a = b")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()
	_, err := parser.ParseSQL(dialect, "SET")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "SET a b")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "SET a =")
	require.Error(t, err)
}

// TestPostgresSetRole tests SET ROLE statements
// Reference: tests/sqlparser_postgres.rs:1702
func TestPostgresSetRole(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SET SESSION ROLE NONE")
	pgAndGeneric.VerifiedStmt(t, "SET LOCAL ROLE \"rolename\"")
	pgAndGeneric.VerifiedStmt(t, "SET ROLE 'rolename'")
}

// TestPostgresShow tests SHOW statements
// Reference: tests/sqlparser_postgres.rs:1746
func TestPostgresShow(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SHOW a a")
	pgAndGeneric.VerifiedStmt(t, "SHOW ALL ALL")
}

// TestPostgresDeallocate tests DEALLOCATE statements
// Reference: tests/sqlparser_postgres.rs:1765
func TestPostgresDeallocate(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DEALLOCATE a")
	pgAndGeneric.VerifiedStmt(t, "DEALLOCATE ALL")
	pgAndGeneric.VerifiedStmt(t, "DEALLOCATE PREPARE a")
	pgAndGeneric.VerifiedStmt(t, "DEALLOCATE PREPARE ALL")
}

// TestPostgresExecute tests EXECUTE statements
// Reference: tests/sqlparser_postgres.rs:1804
func TestPostgresExecute(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "EXECUTE a")
	pgAndGeneric.VerifiedStmt(t, "EXECUTE a(1, 't')")
	pgAndGeneric.VerifiedStmt(t, "EXECUTE a USING CAST(1337 AS SMALLINT), CAST(7331 AS SMALLINT)")
}

// TestPostgresPrepare tests PREPARE statements
// Reference: tests/sqlparser_postgres.rs:1881
func TestPostgresPrepare(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "PREPARE a AS INSERT INTO customers VALUES (a1, a2, a3)")
	pgAndGeneric.VerifiedStmt(t, "PREPARE a (INT, TEXT) AS SELECT * FROM customers WHERE customers.id = a1")
}

// TestPostgresOnConflict tests INSERT ON CONFLICT statements
// Reference: tests/sqlparser_postgres.rs:1948
func TestPostgresOnConflict(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname) VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc') ON CONFLICT(did) DO UPDATE SET dname = EXCLUDED.dname")
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname, area) VALUES (5, 'Gizmo Transglobal', 'Mars'), (6, 'Associated Computing, Inc', 'Venus') ON CONFLICT(did, area) DO UPDATE SET dname = EXCLUDED.dname, area = EXCLUDED.area")
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname) VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc') ON CONFLICT DO NOTHING")
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname, dsize) VALUES (5, 'Gizmo Transglobal', 1000), (6, 'Associated Computing, Inc', 1010) ON CONFLICT(did) DO UPDATE SET dname = $1 WHERE dsize > $2")
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname, dsize) VALUES (5, 'Gizmo Transglobal', 1000), (6, 'Associated Computing, Inc', 1010) ON CONFLICT ON CONSTRAINT distributors_did_pkey DO UPDATE SET dname = $1 WHERE dsize > $2")
}

// TestPostgresReturning tests RETURNING clause
// Reference: tests/sqlparser_postgres.rs:2136
func TestPostgresReturning(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "INSERT INTO distributors (did, dname) VALUES (DEFAULT, 'XYZ Widgets') RETURNING did")
	pgAndGeneric.VerifiedStmt(t, "UPDATE weather SET temp_lo = temp_lo + 1, temp_hi = temp_lo + 15, prcp = DEFAULT WHERE city = 'San Francisco' AND date = '2003-07-03' RETURNING temp_lo AS lo, temp_hi AS hi, prcp")
	pgAndGeneric.VerifiedStmt(t, "DELETE FROM tasks WHERE status = 'DONE' RETURNING *")
}

// TestPostgresJson tests JSON operators
// Reference: tests/sqlparser_postgres.rs:3310
func TestPostgresJson(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT params ->> 'name' FROM events")
	pg.VerifiedStmt(t, "SELECT params -> 'name' FROM events")
	pg.VerifiedStmt(t, "SELECT info -> 'items' ->> 'product' FROM orders")
	pg.VerifiedStmt(t, "SELECT obj -> 42")
	pg.VerifiedStmt(t, "SELECT obj -> key")
	pg.VerifiedStmt(t, "SELECT obj -> 3 * 2")
	pg.VerifiedStmt(t, "SELECT info #> '{a,b,c}' FROM orders")
	pg.VerifiedStmt(t, "SELECT info #>> '{a,b,c}' FROM orders")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info @> '{\"a\": 1}'")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE '{\"a\": 1}' <@ info")
	pg.VerifiedStmt(t, "SELECT info #- ARRAY['a', 'b'] FROM orders")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info @? '$.a'")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info @@ '$.a'")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info ? 'b'")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info ?& ARRAY['b', 'c']")
	pg.VerifiedStmt(t, "SELECT info FROM orders WHERE info ?| ARRAY['b', 'c']")
}

// TestPostgresJsonObjectColonSyntax tests JSON_OBJECT with colon syntax
// Reference: tests/sqlparser_postgres.rs:3540
func TestPostgresJsonObjectColonSyntax(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, "JSON_OBJECT('name' : 'value')")
}

// TestPostgresJsonObjectValueSyntax tests JSON_OBJECT with VALUE syntax
// Reference: tests/sqlparser_postgres.rs:3564
func TestPostgresJsonObjectValueSyntax(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, "JSON_OBJECT('name' VALUE 'value')")
}

// TestPostgresCreateIndex tests CREATE INDEX statements
// Reference: tests/sqlparser_postgres.rs:2634
func TestPostgresCreateIndex(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE INDEX IF NOT EXISTS my_index ON my_table(col1, col2)")
	pg.VerifiedStmt(t, "CREATE INDEX ON my_table(col1, col2)")
}

// TestPostgresCreateIndexConcurrently tests CREATE INDEX CONCURRENTLY
// Reference: tests/sqlparser_postgres.rs:3021
func TestPostgresCreateIndexConcurrently(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE INDEX CONCURRENTLY IF NOT EXISTS my_index ON my_table(col1, col2)")
}

// TestPostgresCreateIndexWithPredicate tests CREATE INDEX with WHERE clause
// Reference: tests/sqlparser_postgres.rs:3056
func TestPostgresCreateIndexWithPredicate(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE INDEX IF NOT EXISTS my_index ON my_table(col1, col2) WHERE col3 IS NULL")
}

// TestPostgresCreateIndexWithInclude tests CREATE INDEX with INCLUDE
// Reference: tests/sqlparser_postgres.rs:3091
func TestPostgresCreateIndexWithInclude(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE INDEX IF NOT EXISTS my_index ON my_table(col1, col2) INCLUDE (col3, col4)")
}

// TestPostgresCreateIndexWithNullsDistinct tests CREATE INDEX with NULLS DISTINCT
// Reference: tests/sqlparser_postgres.rs:3126
func TestPostgresCreateIndexWithNullsDistinct(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE INDEX IF NOT EXISTS my_index ON my_table(col1, col2) NULLS NOT DISTINCT")
	pg.VerifiedStmt(t, "CREATE INDEX IF NOT EXISTS my_index ON my_table(col1, col2) NULLS DISTINCT")
}

// TestPostgresArraySubqueryExpr tests ARRAY with subquery
// Reference: tests/sqlparser_postgres.rs:3195
func TestPostgresArraySubqueryExpr(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT ARRAY(SELECT 1 UNION SELECT 2)")
}

// TestPostgresTransactionStatement tests transaction-related SET statements
// Reference: tests/sqlparser_postgres.rs:3284
func TestPostgresTransactionStatement(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SET TRANSACTION SNAPSHOT '000003A1-1'")
	pg.VerifiedStmt(t, "SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY, READ WRITE, ISOLATION LEVEL SERIALIZABLE")
}

// TestPostgresCompositeValue tests composite value access
// Reference: tests/sqlparser_postgres.rs:3652
func TestPostgresCompositeValue(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT (on_hand.item).name FROM on_hand WHERE (on_hand.item).price > 9")
	pg.VerifiedStmt(t, "SELECT (information_schema._pg_expandarray(ARRAY['i', 'i'])).n")
}

// TestPostgresQuotedIdentifier tests quoted identifiers
// Reference: tests/sqlparser_postgres.rs:3729
func TestPostgresQuotedIdentifier(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT \"quoted \"\" ident\"")
	pgAndGeneric.VerifiedStmt(t, "SELECT \"\"\"quoted ident\"\"\"")
}

// TestPostgresLocalAndGlobal tests LOCAL and GLOBAL keywords
// Reference: tests/sqlparser_postgres.rs:3739
func TestPostgresLocalAndGlobal(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE LOCAL TEMPORARY TABLE table_name (COL INT)")
}

// TestPostgresOnCommit tests ON COMMIT clauses
// Reference: tests/sqlparser_postgres.rs:3744
func TestPostgresOnCommit(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TEMPORARY TABLE table_name (COL INT) ON COMMIT PRESERVE ROWS")
	pgAndGeneric.VerifiedStmt(t, "CREATE TEMPORARY TABLE table_name (COL INT) ON COMMIT DELETE ROWS")
	pgAndGeneric.VerifiedStmt(t, "CREATE TEMPORARY TABLE table_name (COL INT) ON COMMIT DROP")
}

// TestPostgresEscapedLiteralString tests escaped literal strings
// Reference: tests/sqlparser_postgres.rs:3765
func TestPostgresEscapedLiteralString(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedExpr(t, `E's1 \n s1'`)
	pgAndGeneric.VerifiedExpr(t, `E's2 \\n s2'`)
	pgAndGeneric.VerifiedExpr(t, `E's3 \" s3'`)
	pgAndGeneric.VerifiedExpr(t, `E's4 \\\n s4'`)
	pgAndGeneric.VerifiedExpr(t, `E'\''`)
	pgAndGeneric.VerifiedExpr(t, `E'foo \\'`)
	// TODO: Unicode/hex/octal escapes need special serialization to preserve escape sequences
	// pgAndGeneric.VerifiedExpr(t, `E'\u0001'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\U0010FFFF'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\xC'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\x25'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\2'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\45'`)
	// pgAndGeneric.VerifiedExpr(t, `E'\445'`)
}

// TestPostgresDeclare tests DECLARE statements for cursors
// Reference: tests/sqlparser_postgres.rs:3858
func TestPostgresDeclare(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" CURSOR WITH HOLD FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" CURSOR WITHOUT HOLD FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" BINARY CURSOR FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" ASENSITIVE CURSOR FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" INSENSITIVE CURSOR FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" SCROLL CURSOR FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" NO SCROLL CURSOR FOR SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "DECLARE \"SQL_CUR0x7fa44801bc00\" BINARY INSENSITIVE SCROLL CURSOR WITH HOLD FOR SELECT * FROM table_name LIMIT 2222")
}

// TestPostgresCurrentFunctions tests CURRENT_* functions
// Reference: tests/sqlparser_postgres.rs:3875
func TestPostgresCurrentFunctions(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT CURRENT_CATALOG, CURRENT_USER, SESSION_USER, USER")
}

// TestPostgresFetch tests FETCH statements
// Reference: tests/sqlparser_postgres.rs:3933
func TestPostgresFetch(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "FETCH 2048 IN \"SQL_CUR0x7fa44801bc00\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH 2048 IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH NEXT IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH PRIOR IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH FIRST IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH LAST IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH ABSOLUTE 2048 IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH RELATIVE 2048 IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH ALL IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH FORWARD 2048 IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH FORWARD ALL IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH BACKWARD 2048 IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
	pgAndGeneric.VerifiedStmt(t, "FETCH BACKWARD ALL IN \"SQL_CUR0x7fa44801bc00\" INTO \"new_table\"")
}

// TestPostgresCustomOperator tests custom OPERATOR syntax
// Reference: tests/sqlparser_postgres.rs:3957
func TestPostgresCustomOperator(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT * FROM events WHERE relname OPERATOR(database.pg_catalog.~) '^(table)$'")
	pg.VerifiedStmt(t, "SELECT * FROM events WHERE relname OPERATOR(pg_catalog.~) '^(table)$'")
	pg.VerifiedStmt(t, "SELECT * FROM events WHERE relname OPERATOR(~) '^(table)$'")
}

// TestPostgresCreateRole tests CREATE ROLE statements
// Reference: tests/sqlparser_postgres.rs:4018
func TestPostgresCreateRole(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE ROLE IF NOT EXISTS mysql_a, mysql_b")
	pg.VerifiedStmt(t, "CREATE ROLE abc LOGIN PASSWORD NULL")
	pg.VerifiedStmt(t, "CREATE ROLE abc WITH LOGIN PASSWORD NULL")
	pg.VerifiedStmt(t, "CREATE ROLE abc WITH USER foo, bar ROLE baz")
}

// TestPostgresAlterRole tests ALTER ROLE statements
// Reference: tests/sqlparser_postgres.rs:4112
func TestPostgresAlterRole(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "ALTER ROLE old_name RENAME TO new_name")
	pg.VerifiedStmt(t, "ALTER ROLE role_name WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS CONNECTION LIMIT 100 PASSWORD 'abcdef' VALID UNTIL '2025-01-01'")
	pg.VerifiedStmt(t, "ALTER ROLE role_name WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS PASSWORD NULL")
	pg.VerifiedStmt(t, "ALTER ROLE role_name SET maintenance_work_mem FROM CURRENT")
	pg.VerifiedStmt(t, "ALTER ROLE role_name IN DATABASE database_name SET maintenance_work_mem = 100000")
	pg.VerifiedStmt(t, "ALTER ROLE role_name IN DATABASE database_name SET maintenance_work_mem TO 100000")
	pg.VerifiedStmt(t, "ALTER ROLE role_name IN DATABASE database_name SET maintenance_work_mem TO DEFAULT")
	pg.VerifiedStmt(t, "ALTER ROLE role_name RESET ALL")
	pg.VerifiedStmt(t, "ALTER ROLE role_name IN DATABASE database_name RESET maintenance_work_mem")
}

// TestPostgresDelimitedIdentifiers tests delimited identifiers
// Reference: tests/sqlparser_postgres.rs:4330
func TestPostgresDelimitedIdentifiers(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT \"alias\".\"bar baz\", \"myfun\"(), \"simple id\" AS \"column alias\" FROM \"a table\" AS \"alias\"")
	pg.VerifiedStmt(t, "CREATE TABLE \"foo\" (\"bar\" \"int\")")
	pg.VerifiedStmt(t, "ALTER TABLE foo ADD CONSTRAINT \"bar\" PRIMARY KEY (baz)")
	pg.VerifiedStmt(t, "UPDATE foo SET \"bar\" = 5")
}

// TestPostgresUpdateHasKeyword tests UPDATE with reserved keywords as column names
// Reference: tests/sqlparser_postgres.rs:4396
func TestPostgresUpdateHasKeyword(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "UPDATE test SET name=$1, value=$2, where=$3, create=$4, is_default=$5, classification=$6, sort=$7 WHERE id=$8")
}

// TestPostgresUpdateInWithSubquery tests UPDATE in WITH subquery
// Reference: tests/sqlparser_postgres.rs:4411
func TestPostgresUpdateInWithSubquery(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	sql := "WITH \"result\" AS (UPDATE \"Hero\" SET \"name\" = 'Captain America', \"number_of_movies\" = \"number_of_movies\" + 1 WHERE \"secret_identity\" = 'Sam Wilson' RETURNING \"id\", \"name\", \"secret_identity\", \"number_of_movies\") SELECT * FROM \"result\""
	pgAndGeneric.VerifiedStmt(t, sql)
}

// TestPostgresCreateFunctionWithArgs tests CREATE FUNCTION with arguments
// Reference: tests/sqlparser_postgres.rs:4416
func TestPostgresCreateFunctionWithArgs(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	sql := "CREATE OR REPLACE FUNCTION check_strings_different(str1 VARCHAR, str2 VARCHAR) RETURNS BOOLEAN LANGUAGE plpgsql AS $$ BEGIN IF str1 <> str2 THEN RETURN TRUE; ELSE RETURN FALSE; END IF; END; $$"
	pgAndGeneric.VerifiedStmt(t, sql)
}

// TestPostgresCreateFunction tests basic CREATE FUNCTION
// Reference: tests/sqlparser_postgres.rs:4651
func TestPostgresCreateFunction(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	sql := "CREATE FUNCTION add(INTEGER, INTEGER) RETURNS INTEGER LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE AS 'select $1 + $2;'"
	pgAndGeneric.VerifiedStmt(t, sql)
}

// TestPostgresCreateFunctionDetailed tests detailed CREATE FUNCTION variants
// Reference: tests/sqlparser_postgres.rs:4687
func TestPostgresCreateFunctionDetailed(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION add(a INTEGER, IN b INTEGER = 1) RETURNS INTEGER LANGUAGE SQL IMMUTABLE PARALLEL RESTRICTED RETURN a + b")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION add(a INTEGER, IN b INTEGER = 1) RETURNS INTEGER LANGUAGE SQL IMMUTABLE RETURNS NULL ON NULL INPUT PARALLEL RESTRICTED RETURN a + b")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION add(a INTEGER, IN b INTEGER = 1) RETURNS INTEGER LANGUAGE SQL STABLE PARALLEL UNSAFE RETURN a + b")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION add(a INTEGER, IN b INTEGER = 1) RETURNS INTEGER LANGUAGE SQL STABLE CALLED ON NULL INPUT PARALLEL UNSAFE RETURN a + b")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION increment(i INTEGER) RETURNS INTEGER LANGUAGE plpgsql AS $$ BEGIN RETURN i + 1; END; $$")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION no_arg() RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN DELETE FROM my_table; END; $$")
	pgAndGeneric.VerifiedStmt(t, "CREATE OR REPLACE FUNCTION return_table(i INTEGER) RETURNS TABLE(id UUID, is_active BOOLEAN) LANGUAGE plpgsql AS $$ BEGIN RETURN QUERY SELECT NULL::UUID, NULL::BOOLEAN; END; $$")
	pgAndGeneric.OneStatementParsesTo(t, "CREATE FUNCTION add(INTEGER, INTEGER DEFAULT 1) RETURNS INTEGER AS 'select $1 + $2;'", "CREATE FUNCTION add(INTEGER, INTEGER = 1) RETURNS INTEGER AS 'select $1 + $2;'")
}

// TestPostgresCreateFunctionReturnsSetof tests CREATE FUNCTION RETURNS SETOF
// Reference: tests/sqlparser_postgres.rs:4702
func TestPostgresCreateFunctionReturnsSetof(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION get_users() RETURNS SETOF TEXT LANGUAGE sql AS 'SELECT name FROM users'")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION get_ids() RETURNS SETOF INTEGER LANGUAGE sql AS 'SELECT id FROM users'")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION get_all() RETURNS SETOF my_schema.\"MyType\" LANGUAGE sql AS 'SELECT * FROM t'")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION get_rows() RETURNS SETOF RECORD LANGUAGE sql AS 'SELECT * FROM t'")
}

// TestPostgresCreateFunctionWithSecurity tests CREATE FUNCTION with SECURITY
// Reference: tests/sqlparser_postgres.rs:4726
func TestPostgresCreateFunctionWithSecurity(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION test_fn() RETURNS void LANGUAGE sql SECURITY DEFINER AS $$ SELECT 1 $$")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION test_fn() RETURNS void LANGUAGE sql SECURITY INVOKER AS $$ SELECT 1 $$")
}

// TestPostgresCreateFunctionWithSetParams tests CREATE FUNCTION with SET params
// Reference: tests/sqlparser_postgres.rs:4747
func TestPostgresCreateFunctionWithSetParams(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION test_fn() RETURNS void LANGUAGE sql SET search_path = auth, pg_temp, public AS $$ SELECT 1 $$")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION test_fn() RETURNS void LANGUAGE sql SET search_path = public SET statement_timeout = '5s' AS $$ SELECT 1 $$")
	pgAndGeneric.VerifiedStmt(t, "CREATE FUNCTION test_fn() RETURNS void LANGUAGE sql SET search_path FROM CURRENT AS $$ SELECT 1 $$")
}

// TestPostgresDropFunction tests DROP FUNCTION statements
// Reference: tests/sqlparser_postgres.rs:4835
func TestPostgresDropFunction(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "DROP FUNCTION IF EXISTS test_func")
	pg.VerifiedStmt(t, "DROP FUNCTION IF EXISTS test_func(a INTEGER, IN b INTEGER = 1)")
	pg.VerifiedStmt(t, "DROP FUNCTION IF EXISTS test_func1(a INTEGER, IN b INTEGER = 1), test_func2(a VARCHAR, IN b INTEGER = 1)")
}

// TestPostgresDropDomain tests DROP DOMAIN statements
// Reference: tests/sqlparser_postgres.rs:4929
func TestPostgresDropDomain(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "DROP DOMAIN IF EXISTS jpeg_domain")
	pg.VerifiedStmt(t, "DROP DOMAIN jpeg_domain")
	pg.VerifiedStmt(t, "DROP DOMAIN IF EXISTS jpeg_domain CASCADE")
	pg.VerifiedStmt(t, "DROP DOMAIN IF EXISTS jpeg_domain RESTRICT")
}

// TestPostgresDropProcedure tests DROP PROCEDURE statements
// Reference: tests/sqlparser_postgres.rs:4989
func TestPostgresDropProcedure(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "DROP PROCEDURE IF EXISTS test_proc")
	pg.VerifiedStmt(t, "DROP PROCEDURE IF EXISTS test_proc(a INTEGER, IN b INTEGER = 1)")
	pg.VerifiedStmt(t, "DROP PROCEDURE IF EXISTS test_proc1(a INTEGER, IN b INTEGER = 1), test_proc2(a VARCHAR, IN b INTEGER = 1)")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()
	_, err := parser.ParseSQL(dialect, "DROP PROCEDURE testproc DROP")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP PROCEDURE testproc SET NULL")
	require.Error(t, err)
}

// TestPostgresDollarQuotedString tests dollar-quoted strings
// Reference: tests/sqlparser_postgres.rs:5095
func TestPostgresDollarQuotedString(t *testing.T) {
	pg := pg()
	// Canonical form includes AS for aliases
	pg.VerifiedStmt(t, "SELECT $$hello$$, $tag_name$world$tag_name$, $$Foo$Bar$$, $$Foo$Bar$$ AS col_name, $$$$, $tag_name$$tag_name$")
}

// TestPostgresIncorrectDollarQuotedString tests invalid dollar-quoted strings
// Reference: tests/sqlparser_postgres.rs:5183
func TestPostgresIncorrectDollarQuotedString(t *testing.T) {
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "SELECT $x$hello$$")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "SELECT $hello$$")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "SELECT $$$")
	require.Error(t, err)
}

// TestPostgresSelectGroupByGroupingSets tests GROUP BY GROUPING SETS
// Reference: tests/sqlparser_postgres.rs:5195
func TestPostgresSelectGroupByGroupingSets(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT brand, size, sum(sales) FROM items_sold GROUP BY size, GROUPING SETS ((brand), (size), ())")
}

// TestPostgresSelectGroupByRollup tests GROUP BY ROLLUP
// Reference: tests/sqlparser_postgres.rs:5216
func TestPostgresSelectGroupByRollup(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT brand, size, sum(sales) FROM items_sold GROUP BY size, ROLLUP (brand, size)")
}

// TestPostgresSelectGroupByCube tests GROUP BY CUBE
// Reference: tests/sqlparser_postgres.rs:5236
func TestPostgresSelectGroupByCube(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT brand, size, sum(sales) FROM items_sold GROUP BY size, CUBE (brand, size)")
}

// TestPostgresTruncate tests TRUNCATE statements
// Reference: tests/sqlparser_postgres.rs:5256
func TestPostgresTruncate(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE db.table_name")
}

// TestPostgresTruncateWithOptions tests TRUNCATE with options
// Reference: tests/sqlparser_postgres.rs:5279
func TestPostgresTruncateWithOptions(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE TABLE ONLY db.table_name RESTART IDENTITY CASCADE")
}

// TestPostgresTruncateWithTableList tests TRUNCATE with multiple tables
// Reference: tests/sqlparser_postgres.rs:5306
func TestPostgresTruncateWithTableList(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "TRUNCATE TABLE db.table_name, db.other_table_name RESTART IDENTITY CASCADE")
}

// TestPostgresTruncateWithDescendant tests TRUNCATE with descendant tables
// Reference: tests/sqlparser_postgres.rs:5341
func TestPostgresTruncateWithDescendant(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE TABLE t *")
	pgAndGeneric.VerifiedStmt(t, "TRUNCATE TABLE ONLY parent, child *, grandchild RESTART IDENTITY")
}

// TestPostgresSelectRegexpAsColumnName tests REGEXP as column name
// Reference: tests/sqlparser_postgres.rs:5399
func TestPostgresSelectRegexpAsColumnName(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT REGEXP.REGEXP AS REGEXP FROM REGEXP AS REGEXP WHERE REGEXP.REGEXP")
}

// TestPostgresCreateTableWithAlias tests CREATE TABLE with type aliases
// Reference: tests/sqlparser_postgres.rs:5407
func TestPostgresCreateTableWithAlias(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	sql := `CREATE TABLE public.datatype_aliases (
		int8_col INT8,
		int4_col INT4,
		int2_col INT2,
		float8_col FLOAT8,
		float4_col FLOAT4,
		bool_col BOOL
	)`
	pgAndGeneric.VerifiedStmt(t, sql)
}

// TestPostgresCreateTableWithPartitionBy tests CREATE TABLE with PARTITION BY
// Reference: tests/sqlparser_postgres.rs:5470
func TestPostgresCreateTableWithPartitionBy(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t1 (a INT, b TEXT) PARTITION BY RANGE(a)")
}

// TestPostgresJoinConstraintUnnestAlias tests JOIN with UNNEST alias
// Reference: tests/sqlparser_postgres.rs:5512
func TestPostgresJoinConstraintUnnestAlias(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT * FROM t1 JOIN UNNEST(t1.a) AS f ON c1 = c2")
}

// TestPostgresComplexPostgresInsertWithAlias tests complex INSERT with alias
// Reference: tests/sqlparser_postgres.rs:5541
func TestPostgresComplexPostgresInsertWithAlias(t *testing.T) {
	pg := pg()
	sql := `WITH existing AS (SELECT test_table.id FROM test_tables AS test_table WHERE (a = 12) AND (b = 34)), inserted AS (INSERT INTO test_tables AS test_table (id, a, b, c) VALUES (DEFAULT, 56, 78, 90) ON CONFLICT(a, b) DO UPDATE SET c = EXCLUDED.c WHERE (test_table.c <> EXCLUDED.c)) SELECT c FROM existing`
	pg.VerifiedStmt(t, sql)
}

// TestPostgresSimplePostgresInsertWithAlias tests simple INSERT with alias
// Reference: tests/sqlparser_postgres.rs:5549
func TestPostgresSimplePostgresInsertWithAlias(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "INSERT INTO test_tables AS test_table (id, a) VALUES (DEFAULT, 123)")
}

// TestPostgresSimpleInsertWithQuotedAlias tests INSERT with quoted alias
// Reference: tests/sqlparser_postgres.rs:5711
func TestPostgresSimpleInsertWithQuotedAlias(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, `INSERT INTO test_tables AS "Test_Table" (id, a) VALUES (DEFAULT, '0123')`)
}

// TestPostgresArrayAgg tests ARRAY_AGG function
// Reference: tests/sqlparser_postgres.rs:5792
func TestPostgresArrayAgg(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT GREATEST(sections_tbl.*) AS sections FROM sections_tbl")
	pg.VerifiedStmt(t, "SELECT ARRAY_AGG(sections_tbl.*) AS sections FROM sections_tbl")
	pg.VerifiedStmt(t, "SELECT GREATEST(my_schema.sections_tbl.*) AS sections FROM sections_tbl")
	pg.VerifiedStmt(t, "SELECT ARRAY_AGG(my_schema.sections_tbl.*) AS sections FROM sections_tbl")
}

// TestPostgresMatCte tests MATERIALIZED CTEs
// Reference: tests/sqlparser_postgres.rs:5811
func TestPostgresMatCte(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "WITH cte AS MATERIALIZED (SELECT id FROM accounts) SELECT id FROM cte")
	pg.VerifiedStmt(t, "WITH cte AS NOT MATERIALIZED (SELECT id FROM accounts) SELECT id FROM cte")
}

// TestPostgresAtTimeZone tests AT TIME ZONE expressions
// Reference: tests/sqlparser_postgres.rs:5820
func TestPostgresAtTimeZone(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedExpr(t, "CURRENT_TIMESTAMP AT TIME ZONE tz")
	pgAndGeneric.VerifiedExpr(t, "CURRENT_TIMESTAMP AT TIME ZONE ('America/' || 'Los_Angeles')")
}

// TestPostgresIntervalDataType tests INTERVAL data type
// Reference: tests/sqlparser_postgres.rs:5865
func TestPostgresIntervalDataType(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (i INTERVAL)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (i INTERVAL(0))")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (i INTERVAL(6))")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL YEAR")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL MONTH")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL DAY")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL HOUR")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL MINUTE")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL SECOND")
	pgAndGeneric.VerifiedStmt(t, "SELECT '1 second'::INTERVAL YEAR TO MONTH")
}

// TestPostgresIntervalKeywordAsUnquotedIdentifier tests INTERVAL as identifier
// Reference: tests/sqlparser_postgres.rs:5903
func TestPostgresIntervalKeywordAsUnquotedIdentifier(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "SELECT MAX(interval) FROM tbl")
	pg.VerifiedExpr(t, "INTERVAL '1 day'")
}

// TestPostgresCreateTableWithOptions tests CREATE TABLE with WITH options
// Reference: tests/sqlparser_postgres.rs:5909
func TestPostgresCreateTableWithOptions(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TABLE t (c INT) WITH (foo = 'bar', a = 123)")
}

// TestPostgresTableFunctionWithOrdinality tests table function WITH ORDINALITY
// Reference: tests/sqlparser_postgres.rs:5938
func TestPostgresTableFunctionWithOrdinality(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT * FROM generate_series(1, 10) WITH ORDINALITY AS t")
}

// TestPostgresTableUnnestWithOrdinality tests UNNEST with ORDINALITY
// Reference: tests/sqlparser_postgres.rs:5956
func TestPostgresTableUnnestWithOrdinality(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT * FROM UNNEST([10, 20, 30]) WITH ORDINALITY AS t")
}

// TestPostgresEscapedStringLiteral tests escaped string literals
// Reference: tests/sqlparser_postgres.rs:5971
func TestPostgresEscapedStringLiteral(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, `E'\n'`)
}

// TestPostgresCreateDomain tests CREATE DOMAIN statements
// Reference: tests/sqlparser_postgres.rs:5984
func TestPostgresCreateDomain(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE DOMAIN my_domain AS INTEGER CHECK (VALUE > 0)")
	pg.VerifiedStmt(t, "CREATE DOMAIN my_domain AS INTEGER COLLATE \"en_US\" CHECK (VALUE > 0)")
	pg.VerifiedStmt(t, "CREATE DOMAIN my_domain AS INTEGER DEFAULT 1 CHECK (VALUE > 0)")
	pg.VerifiedStmt(t, "CREATE DOMAIN my_domain AS INTEGER COLLATE \"en_US\" DEFAULT 1 CHECK (VALUE > 0)")
	pg.VerifiedStmt(t, "CREATE DOMAIN my_domain AS INTEGER CONSTRAINT my_constraint CHECK (VALUE > 0)")
}

// TestPostgresCreateSimpleBeforeInsertTrigger tests CREATE TRIGGER BEFORE INSERT
// Reference: tests/sqlparser_postgres.rs:6087
func TestPostgresCreateSimpleBeforeInsertTrigger(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TRIGGER check_insert BEFORE INSERT ON accounts FOR EACH ROW EXECUTE FUNCTION check_account_insert")
}

// TestPostgresCreateAfterUpdateTriggerWithCondition tests CREATE TRIGGER AFTER UPDATE with condition
// Reference: tests/sqlparser_postgres.rs:6119
func TestPostgresCreateAfterUpdateTriggerWithCondition(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TRIGGER check_update AFTER UPDATE ON accounts FOR EACH ROW WHEN (NEW.balance > 10000) EXECUTE FUNCTION check_account_update")
}

// TestPostgresCreateInsteadOfDeleteTrigger tests CREATE TRIGGER INSTEAD OF DELETE
// Reference: tests/sqlparser_postgres.rs:6159
func TestPostgresCreateInsteadOfDeleteTrigger(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TRIGGER check_delete INSTEAD OF DELETE ON accounts FOR EACH ROW EXECUTE FUNCTION check_account_deletes")
}

// TestPostgresCreateTriggerWithMultipleEventsAndDeferrable tests CREATE TRIGGER with multiple events
// Reference: tests/sqlparser_postgres.rs:6191
func TestPostgresCreateTriggerWithMultipleEventsAndDeferrable(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE CONSTRAINT TRIGGER check_multiple_events BEFORE INSERT OR UPDATE OR DELETE ON accounts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_account_changes")
}

// TestPostgresCreateTriggerWithReferencing tests CREATE TRIGGER with REFERENCING
// Reference: tests/sqlparser_postgres.rs:6230
func TestPostgresCreateTriggerWithReferencing(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "CREATE TRIGGER check_referencing BEFORE INSERT ON accounts REFERENCING NEW TABLE AS new_accounts OLD TABLE AS old_accounts FOR EACH ROW EXECUTE FUNCTION check_account_referencing")
}

// TestPostgresCreateTriggerInvalidCases tests invalid CREATE TRIGGER syntax
// Reference: tests/sqlparser_postgres.rs:6276
func TestPostgresCreateTriggerInvalidCases(t *testing.T) {
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "CREATE TRIGGER check_update BEFORE UPDATE ON accounts FUNCTION check_account_update")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "CREATE TRIGGER check_update TOMORROW UPDATE ON accounts EXECUTE FUNCTION check_account_update")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "CREATE TRIGGER check_update BEFORE SAVE ON accounts EXECUTE FUNCTION check_account_update")
	require.Error(t, err)
}

// TestPostgresDropTrigger tests DROP TRIGGER statements
// Reference: tests/sqlparser_postgres.rs:6303
func TestPostgresDropTrigger(t *testing.T) {
	pg := pg()
	pg.VerifiedStmt(t, "DROP TRIGGER IF EXISTS check_update ON table_name")
	pg.VerifiedStmt(t, "DROP TRIGGER IF EXISTS check_update ON table_name CASCADE")
	pg.VerifiedStmt(t, "DROP TRIGGER IF EXISTS check_update ON table_name RESTRICT")
	pg.VerifiedStmt(t, "DROP TRIGGER check_update ON table_name")
	pg.VerifiedStmt(t, "DROP TRIGGER check_update ON table_name CASCADE")
	pg.VerifiedStmt(t, "DROP TRIGGER check_update ON table_name RESTRICT")
}

// TestPostgresDropTriggerInvalidCases tests invalid DROP TRIGGER syntax
// Reference: tests/sqlparser_postgres.rs:6331
func TestPostgresDropTriggerInvalidCases(t *testing.T) {
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "DROP TRIGGER check_update ON table_name CASCADE RESTRICT")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP TRIGGER check_update ON table_name CASCADE CASCADE")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP TRIGGER check_update ON table_name CASCADE CASCADE CASCADE")
	require.Error(t, err)
}

// TestPostgresUnicodeStringLiteral tests Unicode string literals
// Reference: tests/sqlparser_postgres.rs:6594
func TestPostgresUnicodeStringLiteral(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedExpr(t, `U&'\0441\043B\043E\043D'`)
	pgAndGeneric.VerifiedExpr(t, `U&'\+01F418'`)
	pgAndGeneric.VerifiedExpr(t, `U&'\\'`)
	pgAndGeneric.VerifiedExpr(t, `U&''''`)
}

// TestPostgresArrowPrecedence tests arrow operator precedence
// Reference: tests/sqlparser_postgres.rs:6641
func TestPostgresArrowPrecedence(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, "foo -> 'bar' = 'spam'")
}

// TestPostgresLongArrowPrecedence tests long arrow operator precedence
// Reference: tests/sqlparser_postgres.rs:6647
func TestPostgresLongArrowPrecedence(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, "foo ->> 'bar' = 'spam'")
}

// TestPostgresArrowCastPrecedence tests arrow with cast precedence
// Reference: tests/sqlparser_postgres.rs:6652
func TestPostgresArrowCastPrecedence(t *testing.T) {
	pg := pg()
	pg.VerifiedExpr(t, "foo -> 'bar'::TEXT")
}

// TestPostgresCreateTypeAsEnum tests CREATE TYPE AS ENUM
// Reference: tests/sqlparser_postgres.rs:6678
func TestPostgresCreateTypeAsEnum(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TYPE public.my_type AS ENUM ('label1', 'label2', 'label3', 'label4')")
}

// TestPostgresAlterType tests ALTER TYPE statements
// Reference: tests/sqlparser_postgres.rs:6700
func TestPostgresAlterType(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type RENAME TO my_new_type")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE IF NOT EXISTS 'label3.5' BEFORE 'label4'")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE 'label3.5' BEFORE 'label4'")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE IF NOT EXISTS 'label3.5' AFTER 'label3'")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE 'label3.5' AFTER 'label3'")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE IF NOT EXISTS 'label5'")
	pgAndGeneric.VerifiedStmt(t, "ALTER TYPE public.my_type ADD VALUE 'label5'")
}

// TestPostgresBitstringLiteral tests bit string literals
// Reference: tests/sqlparser_postgres.rs:6791
func TestPostgresBitstringLiteral(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SELECT B'111'")
}

// TestPostgresVarbitDatatype tests VARBIT data type
// Reference: tests/sqlparser_postgres.rs:6802
func TestPostgresVarbitDatatype(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE foo (x VARBIT, y VARBIT(42))")
}

// TestPostgresAlterTableReplicaIdentity tests ALTER TABLE REPLICA IDENTITY
// Reference: tests/sqlparser_postgres.rs:6826
func TestPostgresAlterTableReplicaIdentity(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo REPLICA IDENTITY FULL")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo REPLICA IDENTITY USING INDEX foo_idx")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo REPLICA IDENTITY NOTHING")
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo REPLICA IDENTITY DEFAULT")
}

// TestPostgresTsDatatypes tests TSVECTOR and TSQUERY data types
// Reference: tests/sqlparser_postgres.rs:6877
func TestPostgresTsDatatypes(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE foo (x TSVECTOR)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE foo (x TSQUERY)")
}

// TestPostgresAlterTableConstraintNotValid tests ALTER TABLE with NOT VALID
// Reference: tests/sqlparser_postgres.rs:6908
func TestPostgresAlterTableConstraintNotValid(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo ADD CONSTRAINT bar FOREIGN KEY (baz) REFERENCES other(ref) NOT VALID")
}

// TestPostgresAlterTableValidateConstraint tests ALTER TABLE VALIDATE CONSTRAINT
// Reference: tests/sqlparser_postgres.rs:6937
func TestPostgresAlterTableValidateConstraint(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER TABLE foo VALIDATE CONSTRAINT bar")
}

// TestPostgresCreateServer tests CREATE SERVER statements
// Reference: tests/sqlparser_postgres.rs:6950
func TestPostgresCreateServer(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE SERVER myserver FOREIGN DATA WRAPPER postgres_fdw")
	pgAndGeneric.VerifiedStmt(t, "CREATE SERVER IF NOT EXISTS myserver TYPE 'server_type' VERSION 'server_version' FOREIGN DATA WRAPPER postgres_fdw")
	pgAndGeneric.VerifiedStmt(t, "CREATE SERVER myserver2 FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'foo', dbname 'foodb', port '5432')")
}

// TestPostgresAlterSchema tests ALTER SCHEMA statements
// Reference: tests/sqlparser_postgres.rs:7029
func TestPostgresAlterSchema(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER SCHEMA foo RENAME TO bar")
	pgAndGeneric.VerifiedStmt(t, "ALTER SCHEMA foo OWNER TO bar")
	pgAndGeneric.VerifiedStmt(t, "ALTER SCHEMA foo OWNER TO CURRENT_ROLE")
	pgAndGeneric.VerifiedStmt(t, "ALTER SCHEMA foo OWNER TO CURRENT_USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER SCHEMA foo OWNER TO SESSION_USER")
}

// TestPostgresForeignKeyMatch tests foreign key MATCH clauses
// Reference: tests/sqlparser_postgres.rs:7068
func TestPostgresForeignKeyMatch(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT REFERENCES other_table (id) MATCH FULL)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT REFERENCES other_table (id) MATCH SIMPLE)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT REFERENCES other_table (id) MATCH PARTIAL)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT, FOREIGN KEY (id) REFERENCES other_table(id) MATCH FULL)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT, FOREIGN KEY (id) REFERENCES other_table(id) MATCH SIMPLE)")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE t (id INT, FOREIGN KEY (id) REFERENCES other_table(id) MATCH PARTIAL)")
}

// TestPostgresForeignKeyMatchWithActions tests foreign key MATCH with actions
// Reference: tests/sqlparser_postgres.rs:7109
func TestPostgresForeignKeyMatchWithActions(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	sql := "CREATE TABLE orders (order_id INT REFERENCES another_table (id) MATCH FULL ON DELETE CASCADE ON UPDATE RESTRICT, customer_id INT, CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) MATCH SIMPLE ON DELETE SET NULL ON UPDATE CASCADE)"
	pgAndGeneric.VerifiedStmt(t, sql)
}

// TestPostgresCreateOperator tests CREATE OPERATOR statements
// Reference: tests/sqlparser_postgres.rs:7116
func TestPostgresCreateOperator(t *testing.T) {
	pg := pg()
	sql := "CREATE OPERATOR myschema.@@ (PROCEDURE = myschema.my_proc, LEFTARG = TIMESTAMP WITH TIME ZONE, RIGHTARG = VARCHAR(255), COMMUTATOR = schema.>, NEGATOR = schema.<=, RESTRICT = myschema.sel_func, JOIN = myschema.join_func, HASHES, MERGES)"
	pg.VerifiedStmt(t, sql)

	// Test various operator symbols
	operators := []string{"-", "*", "/", "<", ">", "=", "<=", ">=", "<>", "||", "&&", "<<", ">>"}
	for _, op := range operators {
		sql := "CREATE OPERATOR " + op + " (FUNCTION = f)"
		pg.VerifiedStmt(t, sql)
	}

	pg.OneStatementParsesTo(t, "CREATE OPERATOR != (FUNCTION = func)", "CREATE OPERATOR <> (FUNCTION = func)")
	pg.OneStatementParsesTo(t, "CREATE OPERATOR + (FUNCTION = f, COMMUTATOR = OPERATOR(>), NEGATOR = OPERATOR(>=))", "CREATE OPERATOR + (FUNCTION = f, COMMUTATOR = >, NEGATOR = >=)")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	// Duplicate FUNCTION clause
	_, err := parser.ParseSQL(dialect, "CREATE OPERATOR + (FUNCTION = f, FUNCTION = f2)")
	require.Error(t, err)

	// Missing FUNCTION clause
	_, err = parser.ParseSQL(dialect, "CREATE OPERATOR + (LEFTARG = INT4)")
	require.Error(t, err)

	// Empty parameter list
	_, err = parser.ParseSQL(dialect, "CREATE OPERATOR + ()")
	require.Error(t, err)
}

// TestPostgresDropOperator tests DROP OPERATOR statements
// Reference: tests/sqlparser_postgres.rs:7234
func TestPostgresDropOperator(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR ~ (NONE, BIT)")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR < (INTEGER, INTEGER)")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR IF EXISTS < (INTEGER, INTEGER)")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR < (INTEGER, INTEGER) CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR < (INTEGER, INTEGER) RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR myschema.@@ (TEXT, TEXT)")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR IF EXISTS + (INTEGER, INTEGER), - (INTEGER, INTEGER) CASCADE")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "DROP OPERATOR (INTEGER, INTEGER)")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP OPERATOR IF EXISTS (INTEGER, INTEGER)")
	require.Error(t, err)
}

// TestPostgresAlterOperator tests ALTER OPERATOR statements
// Reference: tests/sqlparser_postgres.rs:7328
func TestPostgresAlterOperator(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (INTEGER, INTEGER) OWNER TO joe")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (INTEGER, INTEGER) OWNER TO CURRENT_USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (INTEGER, INTEGER) OWNER TO CURRENT_ROLE")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (INTEGER, INTEGER) OWNER TO SESSION_USER")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR ~ (NONE, BIT) OWNER TO joe")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR @@ (TEXT, TEXT) OWNER TO joe")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (TEXT, TEXT) SET SCHEMA new_schema")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR myschema.@@ (TEXT, TEXT) SET SCHEMA other_schema")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR && (TEXT, TEXT) SET (RESTRICT = _int_contsel, JOIN = _int_contjoinsel)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR && (TEXT, TEXT) SET (RESTRICT = NONE, JOIN = my_joinsel)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR && (TEXT, TEXT) SET (RESTRICT = my_sel, JOIN = NONE)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR && (INTEGER, INTEGER) SET (COMMUTATOR = &&, NEGATOR = >)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR + (INTEGER, INTEGER) SET (COMMUTATOR = +, NEGATOR = -, HASHES, MERGES)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR = (INTEGER, INTEGER) SET (HASHES)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR < (INTEGER, INTEGER) SET (MERGES)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR <= (INTEGER, INTEGER) SET (HASHES, MERGES)")
}

// TestPostgresAlterOperatorFamily tests ALTER OPERATOR FAMILY statements
// Reference: tests/sqlparser_postgres.rs:7524
func TestPostgresAlterOperatorFamily(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY integer_ops USING btree ADD OPERATOR 1 < (INT4, INT2)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY text_ops USING btree ADD OPERATOR 1 @@ (TEXT, TEXT) FOR SEARCH")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY integer_ops USING btree ADD FUNCTION 1 btint42cmp(INT4, INT2)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY integer_ops USING btree DROP OPERATOR 1 (INT4, INT2)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY integer_ops USING btree DROP FUNCTION 1 (INT4, INT2)")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY old_ops USING btree RENAME TO new_ops")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY my_ops USING btree OWNER TO joe")
	pgAndGeneric.VerifiedStmt(t, "ALTER OPERATOR FAMILY my_ops USING btree SET SCHEMA new_schema")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "ALTER OPERATOR FAMILY my_ops ADD OPERATOR 1 < (INT4, INT2)")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "ALTER OPERATOR FAMILY my_ops USING btree INVALID_OPERATION")
	require.Error(t, err)
}

// TestPostgresDropOperatorFamily tests DROP OPERATOR FAMILY statements
// Reference: tests/sqlparser_postgres.rs:8064
func TestPostgresDropOperatorFamily(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY float_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY IF EXISTS float_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY float_ops USING btree CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY float_ops USING btree RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY myschema.custom_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR FAMILY ops1, ops2, schema.ops3 USING btree")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "DROP OPERATOR FAMILY USING btree")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP OPERATOR FAMILY IF EXISTS USING btree")
	require.Error(t, err)
}

// TestPostgresDropOperatorClass tests DROP OPERATOR CLASS statements
// Reference: tests/sqlparser_postgres.rs:8127
func TestPostgresDropOperatorClass(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS widget_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS IF EXISTS widget_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS widget_ops USING btree CASCADE")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS widget_ops USING btree RESTRICT")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS myschema.int4_ops USING btree")
	pgAndGeneric.VerifiedStmt(t, "DROP OPERATOR CLASS ops1, ops2, schema.ops3 USING btree")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "DROP OPERATOR CLASS USING btree")
	require.Error(t, err)

	_, err = parser.ParseSQL(dialect, "DROP OPERATOR CLASS IF EXISTS USING btree")
	require.Error(t, err)
}

// TestPostgresCreateOperatorFamily tests CREATE OPERATOR FAMILY statements
// Reference: tests/sqlparser_postgres.rs:8189
func TestPostgresCreateOperatorFamily(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING btree")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING hash")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING gist")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING gin")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING spgist")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY my_family USING brin")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR FAMILY myschema.test_family USING btree")
}

// TestPostgresCreateOperatorClass tests CREATE OPERATOR CLASS statements
// Reference: tests/sqlparser_postgres.rs:8214
func TestPostgresCreateOperatorClass(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS int4_ops FOR TYPE INT4 USING btree AS OPERATOR 1 <")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS int4_ops DEFAULT FOR TYPE INT4 USING btree AS OPERATOR 1 <")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS int4_ops FOR TYPE INT4 USING btree FAMILY int4_family AS OPERATOR 1 <")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS myschema.test_ops FOR TYPE INT4 USING btree AS OPERATOR 1 <")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS CAS_btree_ops DEFAULT FOR TYPE CAS USING btree FAMILY CAS_btree_ops AS OPERATOR 1 <, OPERATOR 2 <=, OPERATOR 3 =, OPERATOR 4 >=, OPERATOR 5 >, FUNCTION 1 cas_cmp(CAS, CAS)")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING gist AS OPERATOR 1 < (INT4, INT4)")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING gist AS OPERATOR 1 < FOR SEARCH")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING gist AS OPERATOR 2 <<-> FOR ORDER BY float_ops")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING btree AS FUNCTION 1 (INT4, INT4) btcmp(INT4, INT4)")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING btree AS FUNCTION 1 my_func")
	pgAndGeneric.VerifiedStmt(t, "CREATE OPERATOR CLASS gist_ops FOR TYPE geometry USING gist AS OPERATOR 1 <<, FUNCTION 1 gist_consistent(internal, geometry, INT4), STORAGE box")

	// Test error cases
	dialect := postgresql.NewPostgreSqlDialect()

	_, err := parser.ParseSQL(dialect, "CREATE OPERATOR CLASS test_ops FOR TYPE INT4 USING btree AS FUNCTION 1 cas_cmp(()")
	require.Error(t, err)
}

// TestPostgresIdentifiersSemicolonHandling tests identifier handling with semicolons
// Reference: tests/sqlparser_postgres.rs:8448
func TestPostgresIdentifiersSemicolonHandling(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "SHOW search_path; SELECT 1")
	pgAndGeneric.VerifiedStmt(t, "SHOW search_path; SHOW ALL; SHOW ALL")
}

// TestPostgresCreateTablePartitionOfRange tests CREATE TABLE PARTITION OF with RANGE
// Reference: tests/sqlparser_postgres.rs:8456
func TestPostgresCreateTablePartitionOfRange(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE measurement_y2006m02 PARTITION OF measurement FOR VALUES FROM ('2006-02-01') TO ('2006-03-01')")
}

// TestPostgresCreateTablePartitionOfRangeWithMinvalueMaxvalue tests CREATE TABLE PARTITION OF with MINVALUE/MAXVALUE
// Reference: tests/sqlparser_postgres.rs:8492
func TestPostgresCreateTablePartitionOfRangeWithMinvalueMaxvalue(t *testing.T) {
	pgAndGeneric := pgAndGeneric()
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE orders_old PARTITION OF orders FOR VALUES FROM (MINVALUE) TO ('2020-01-01')")
	pgAndGeneric.VerifiedStmt(t, "CREATE TABLE orders_new PARTITION OF orders FOR VALUES FROM ('2024-01-01') TO (MAXVALUE)")
}
